# Generated by Django 4.2.2 on 2024-12-13 08:19

import core.custom_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='*Nicknames can contain only letters and digits.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), core.custom_validators.validate_letters_digits_string])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('country', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
