# Generated by Django 4.2.2 on 2024-12-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travelers',
            new_name='Traveler',
        ),
    ]
