# Generated by Django 4.2.2 on 2024-12-13 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('summary', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField(default=1, help_text='*Duration in days is expected.')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
