# Generated by Django 4.2.2 on 2024-12-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_rename_travelers_traveler'),
        ('trip', '0003_alter_trip_traveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='traveler.traveler'),
        ),
    ]
